/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-container':       '#045047',
        'surface-container':         '#1e2022',
        'on-secondary-container':    '#82c1b5',
        'on-surface-variant':        '#dfc0b7',
        'surface-dim':               '#121416',
        'outline':                   '#a68b82',
        'surface-container-highest': '#333537',
        'on-background':             '#e2e2e5',
        'error-container':           '#93000a',
        'secondary':                 '#94d2c7',
        'surface-container-lowest':  '#0c0e10',
        'on-primary':                '#5d1800',
        'surface':                   '#121416',
        'inverse-surface':           '#e2e2e5',
        'on-error-container':        '#ffdad6',
        'tertiary-container':        '#ab5c00',
        'on-tertiary-container':     '#fff4ee',
        'on-surface':                '#e2e2e5',
        'primary':                   '#ffb59d',
        'primary-container':         '#be4d25',
        'surface-bright':            '#37393b',
        'inverse-on-surface':        '#2f3133',
        'background':                '#121416',
        'surface-container-low':     '#1a1c1e',
        'surface-container-high':    '#282a2c',
        'surface-variant':           '#333537',
        'outline-variant':           '#57423b',
        'on-tertiary':               '#4d2600',
        'on-secondary':              '#003731',
        'on-primary-container':      '#fff4f1',
        'tertiary':                  '#ffb77d',
        'error':                     '#ffb4ab',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '0px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        mono:     ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
    },
  },
  plugins: [],
}
