#!/usr/bin/env bash
# clean-session-artifacts.sh
# Moves vuemorphic session artifacts to trash (never rm).
# Safe to run anytime — only targets known-regenerable files.

set -e
cd "$(dirname "$0")/.."
ROOT=$(pwd)

# macOS uses /usr/bin/trash, Linux uses trash-put
TRASH=$(which trash 2>/dev/null || which trash-put 2>/dev/null || echo "")
if [ -z "$TRASH" ]; then
  echo "ERROR: no trash command found (install 'trash' on macOS or 'trash-cli' on Linux)"
  exit 1
fi

echo "Cleaning session artifacts in: $ROOT"

# Compare output screenshots (regenerated by compare/compare.py)
for dir in "$ROOT"/compare-output "$ROOT"/compare-output-*; do
  [ -d "$dir" ] && { echo "  trash $(basename $dir)/"; $TRASH "$dir"; }
done

# Phase B prompt/response logs (regenerated on next run)
[ -d "$ROOT/_prompt_logs" ] && { echo "  trash _prompt_logs/"; $TRASH "$ROOT/_prompt_logs"; }

# Extracted Vue SFC snippets (committed to corpora/claude-design-vue)
[ -d "$ROOT/snippets" ] && { echo "  trash snippets/"; $TRASH "$ROOT/snippets"; }

# Session planning/handoff docs
[ -f "$ROOT/PLAN.md" ] && { echo "  trash PLAN.md"; $TRASH "$ROOT/PLAN.md"; }
[ -f "$ROOT/docs/session-handoff.md" ] && { echo "  trash docs/session-handoff.md"; $TRASH "$ROOT/docs/session-handoff.md"; }

# Runtime state (regenerated by phase-a / phase-b)
[ -f "$ROOT/conversion_manifest.json" ] && { echo "  trash conversion_manifest.json"; $TRASH "$ROOT/conversion_manifest.json"; }
[ -f "$ROOT/review_queue.json" ] && { echo "  trash review_queue.json"; $TRASH "$ROOT/review_queue.json"; }
[ -f "$ROOT/vuemorphic.db" ] && { echo "  trash vuemorphic.db"; $TRASH "$ROOT/vuemorphic.db"; }
[ -f "$ROOT/vuemorphic.db.bak" ] && { echo "  trash vuemorphic.db.bak"; $TRASH "$ROOT/vuemorphic.db.bak"; }

echo "Done. Run 'vuemorphic phase-a' to regenerate the DB if needed."
